name: Build and Test

on:
    push:
    pull_request:

defaults:
  run:
    shell: bash

permissions:
  id-token: write

jobs:
    build:
        name: Build and test code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                node-version: '20.x'
                registry-url: 'https://registry.npmjs.org'

            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
                  registry-url: "https://registry.npmjs.org"

            - name: Install packages
              run: bun install
            - name: Build code
              run: bun run build

            - name: Test
              run: bun run test

            - name: 'Publish'
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                npm publish --provenance --access=public